### ISSUE TITLE
🛠 Tooling: Feature template includes Bug Report checklist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [omnidan/node-emoji#195]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/omnidan/node-emoji/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Coming over from #194, the _feature_ issue template includes _bug_-specific checklist items:

https://github.com/omnidan/node-emoji/blob/186a0acadf1620d486592eb466e376179d36aa4d/.github/ISSUE_TEMPLATE/03-feature.yml?plain=1#L4-L11

### Additional Info

Originally reported in https://github.com/JoshuaKGoldberg/create-typescript-app/issues/1287
